/* This file is generated by web/scripts/generate-openapi.mjs. Do not edit manually. */

export interface components {
  schemas: {
    PlatformStatus: {
      service: string;
      status: string;
      timestamp: string;
    };
  };
}

export interface paths {
  '/api/v1/status': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['PlatformStatus'];
          };
        };
      };
    };
  };
}
