import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const openApiUrl = process.env.OPENAPI_URL ?? 'http://localhost:8080/v3/api-docs';
const destination = resolve(import.meta.dirname, '../src/api/generated.ts');
const response = await fetch(openApiUrl);

if (!response.ok) {
  throw new Error(`Could not read the backend OpenAPI document: ${response.status} ${response.statusText}`);
}

const document = await response.json();
const statusSchema = document.components?.schemas?.PlatformStatus;
const statusOperation = document.paths?.['/api/v1/status']?.get;

if (document.openapi !== '3.1.1' || statusSchema?.type !== 'object' || statusOperation?.operationId !== 'getPlatformStatus') {
  throw new Error('The backend OpenAPI document does not contain the expected status contract.');
}

const requiredProperties = new Set(statusSchema.required ?? []);
const statusProperties = Object.entries(statusSchema.properties ?? {}).sort(([left], [right]) => left.localeCompare(right));

if (statusProperties.length === 0) {
  throw new Error('The backend OpenAPI document does not define the status response properties.');
}

const typeFor = (schema) => {
  if (schema.type === 'string') {
    return 'string';
  }
  if (schema.type === 'integer' || schema.type === 'number') {
    return 'number';
  }
  if (schema.type === 'boolean') {
    return 'boolean';
  }
  throw new Error(`Unsupported OpenAPI type in the status contract: ${schema.type}`);
};

const properties = statusProperties
  .map(([name, schema]) => {
    const optional = requiredProperties.has(name) ? '' : '?';
    return `      ${name}${optional}: ${typeFor(schema)};`;
  })
  .join('\n');

const generated = `/* This file is generated by web/scripts/generate-openapi.mjs. Do not edit manually. */

export interface components {
  schemas: {
    PlatformStatus: {
${properties}
    };
  };
}

export interface paths {
  '/api/v1/status': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['PlatformStatus'];
          };
        };
      };
    };
  };
}
`;

await writeFile(destination, generated, 'utf8');
